services:
  - type: web
    name: user-service
    env: docker
    repo: https://github.com/anilmondi/ELEARN
    branch: main
    rootDir: Backend/user-service
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:mysql://localhost:3306/elearn
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: Anilmondi@45
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin
      - key: EUREKA_PORT
        value: "8761"
      - key: USER_SERVICE_NAME
        value: user-service
      - key: USER_SERVICE_PORT
        value: "8085"
